# Set to True to run cellranger mkfastq
makefastq: True
# Set to True to run cellranger count
getcounts: True
# Set to True to print out commands
showcmd: True

# Cell Ranger binary
cranger    : /opt/NGS/cellranger/cellranger-3.1.0/cellranger
# Path to cellranger reference files
refdir     : /mnt/data1/Annotation/cellranger/refdata-cellranger-GRCh38-3.0.0/

# Path to bcl2fastq
bcl2fastq  : /opt/Anaconda3-2019.10/pkgs/bcl2fastq2-2.20.0.422-2/bin/

# Path to project input data directory
datadir    : /mnt/data1/Genomic/191011_COOPER_0294_BH7NF5BBXY/
# Path to directory for Popen stdout and stderr files
logdir     : ./outlog/
#Path to directory for the output
outdir     : ./output/
# Path to output directory
projid     : WestProject
# If set to null, the sample ids will be taken from sample sheet
# Otherwise provide python list e.g., ['sampid1', 'sampid2']
sampleids : null
# Samplefile csv file (will be ignored if sampleids not set to null
sampsheet : 191011_COOPER_0294_BH7NF5BBXY_L2_Sample_Sheet.csv
# The sample ids will be extracted from this column of the sample sheet
# Note that this is case sensitive
sampidcol : Sample_ID
# Some sample sheets have pre-ambles. need to specify the number of rows
# to skip
sampskip  : 7
# The delimiter for the sample sheet
sampdelim : ","

# Popen will submit cjobs at a time
cjobs  : 5
# The number of cores to be used for each sample
ccores : 8
# The number of cores to be used during mkfastq. 
# It is likely that the optimal number is the number of samples
# This needs to researched as cellraner provides additional threading
# options
fcores : 5
# The number of targeted cells. Typically, 10000
ncells : 10000
